// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH4ZfbCkn9OXoXwQY8jF-zY8y0sEkVJFQ',
    appId: '1:39607892365:web:66fca8217571f28c1725c4',
    messagingSenderId: '39607892365',
    projectId: 'shopping-app-ceace',
    authDomain: 'shopping-app-ceace.firebaseapp.com',
    storageBucket: 'shopping-app-ceace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZJYP0F9cfpbAXTHE0L3VX6TI0fXrPoA',
    appId: '1:39607892365:android:21e965afc3a394d51725c4',
    messagingSenderId: '39607892365',
    projectId: 'shopping-app-ceace',
    storageBucket: 'shopping-app-ceace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoB1mcO7kGntx0QFpbQokC4rJSImfijFY',
    appId: '1:39607892365:ios:f0da4a381d2d0b4e1725c4',
    messagingSenderId: '39607892365',
    projectId: 'shopping-app-ceace',
    storageBucket: 'shopping-app-ceace.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoB1mcO7kGntx0QFpbQokC4rJSImfijFY',
    appId: '1:39607892365:ios:93c501b1bf903bbb1725c4',
    messagingSenderId: '39607892365',
    projectId: 'shopping-app-ceace',
    storageBucket: 'shopping-app-ceace.appspot.com',
    iosBundleId: 'com.example.shopApp.RunnerTests',
  );
}
